### 1. Array Creation

### Create a 1-dimensional array of integers from 1 to 10

In [2]:
import numpy as np
array_1_to_10 = np.arange(1,11)
array_1_to_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create a 2-dimensional array with random float values of shape (3, 4).

In [8]:
array_2d = np.random.rand(3,4)
array_2d

array([[0.14357289, 0.76938486, 0.81967322, 0.56468568],
       [0.83089414, 0.75492721, 0.088466  , 0.92492148],
       [0.2572619 , 0.58021035, 0.72185253, 0.56774537]])

### Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [12]:
array_3d = np.zeros((2,3,4))
array_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 2. Array Operations

### Given two 1-dimensional arrays, perform element-wise addition,

subtractin, multiplication, and division.

In [27]:
import numpy as np
array1=np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
a = array1 + array2
b= array1 - array2
c= array1 * array2
d= array1 / array2
a
b
c
d

array([ 5, 12, 21, 32])

### Calculate the mean, median, and standard deviation of a given 1-
dimensional array. 

In [34]:
import numpy as np
array = np.array([1,2,3,4])
mean = np.mean(array)
median = np.median(array)
st = np.std(array)
mean
median
st

1.118033988749895

### Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).

In [38]:
array = np.random.rand(1,12)
array_2 = array.reshape(3,4)
array_2

array([[0.73378419, 0.79424075, 0.12453123, 0.21345917],
       [0.36745159, 0.95474677, 0.96149599, 0.23285996],
       [0.09399651, 0.38243156, 0.16683221, 0.32239918]])

### 3. Array Indexing and Slicing:

### Extract the first row and last column of a 2-dimensional array.

In [52]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0,:]
array[:,-1]

array([3, 6, 9])

### Reverse the order of elements in a 1-dimensional array.

In [54]:
array = np.array([1,2,3,4,5])
reversed_array = array[::-1]
reversed_array

array([5, 4, 3, 2, 1])

In [56]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
value = 5
value1 = array>value
selected_elements = array[value1]
selected_elements

array([6, 7, 8, 9])

### Array broadcasting

In [57]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar_value = 10
array1 = scalar_value + array
array1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### multiply a 1-dimensional array with a 2-dimensional array,leveraging numpy's broadcasting rule

In [61]:
array1 = np.array([1,2,3])
array2= np.array([[4,5,6],[7,8,9]])
result_array = array1[:,np.newaxis]*array_2d
result_array

array([[0.14357289, 0.76938486, 0.81967322, 0.56468568],
       [1.66178827, 1.50985442, 0.176932  , 1.84984296],
       [0.77178569, 1.74063104, 2.16555758, 1.70323611]])

### linear Algebra 

In [62]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
dot_product = np.dot(array1, array2)
dot_product

32

### find the inverse and determinant of a square matrix

In [63]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
determinant = np.linalg.det(matrix)
determinant

-9.51619735392994e-16